"use client";
import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { COMMUNITY_POLICY_VERSION, communityRules, reportReasons, type ContentKind } from '@studify/study-core/community-policy';
import { isSupabaseConfigured } from '@/lib/supabase/config';
import { getSupabaseClient } from '@/lib/supabase/client';
import { useStudyData } from '@/lib/study-store';
import { useSocial } from '@/lib/social-store';
type Policy={version:string;support_email:string;enabled:boolean};
type Status={moderator?:boolean;suspended:boolean;reviews:{kind:string;id:string;status:string}[]};
const Context=createContext<{userId:string;status:Status;refresh:()=>Promise<void>}|null>(null);
export function CommunitySafety({children}:{children:ReactNode}){
 const study = useStudyData();
 const [policy,setPolicy]=useState<Policy|null>(null),[status,setStatus]=useState<Status>({suspended:false,reviews:[]}),[accepted,setAccepted]=useState(false),[checked,setChecked]=useState(false),[userId,setUserId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const active=useRef(true),generation=useRef(0);
 const refresh=useCallback(async()=>{const id=++generation.current;try{const db=getSupabaseClient();const {data:auth,error:authError}=await db.auth.getUser();if(authError||!auth.user)throw new Error('Entre na sua conta para abrir a Comunidade.');const results=await Promise.all([db.from('community_policy').select('version,support_email,enabled').single(),db.from('community_acceptances').select('version').eq('user_id',auth.user.id).eq('version',COMMUNITY_POLICY_VERSION),db.rpc('community_my_status')]);for(const result of results)if(result.error)throw result.error;if(active.current&&generation.current===id){setUserId(auth.user.id);setPolicy(results[0].data as Policy);setAccepted(Boolean(results[1].data?.length));setStatus(results[2].data);setError('');}}catch{if(active.current&&generation.current===id){setPolicy(null);setAccepted(false);setError('A Comunidade não está disponível. Confira sua sessão ou tente após a atualização do serviço.');}}},[]);
 useEffect(()=>{if(!isSupabaseConfigured()) return; const ref=generation;active.current=true;const timer=setTimeout(()=>void refresh(),0);const {data:auth}=getSupabaseClient().auth.onAuthStateChange(()=>{generation.current++;setPolicy(null);setAccepted(false);setTimeout(()=>{if(active.current)void refresh();},0);});const failure=(event:Event)=>setError((event as CustomEvent<string>).detail);window.addEventListener('studify-social-error',failure);return()=>{clearTimeout(timer);active.current=false;ref.current++;auth.subscription.unsubscribe();window.removeEventListener('studify-social-error',failure);};},[refresh]);
 async function accept(){setBusy(true);try{const {error}=await getSupabaseClient().rpc('community_accept_terms',{p_version:COMMUNITY_POLICY_VERSION});if(error)throw error;await refresh();}catch{setError('Não foi possível registrar o aceite. Tente novamente.');}finally{setBusy(false);}}
 const allowed=study.ready&&study.mode==='cloud'&&study.userId===userId&&policy?.enabled&&policy.version===COMMUNITY_POLICY_VERSION&&accepted&&!status.suspended;
 if(study.mode === "local") return <>{children}</>;
 return <><section className="mx-auto max-w-3xl space-y-3 p-4"><Link className="text-accent" href="/regras-comunidade">Regras e contato de suporte</Link>{status.moderator&&study.userId===userId&&<Link className="ml-4 text-accent" href="/moderacao">Abrir moderação</Link>}{error&&<p role="alert">{error}</p>}{!policy?<button onClick={()=>void refresh()}>Atualizar Comunidade</button>:!policy.enabled?<p>Comunidade aguardando configuração operacional. É necessário cadastrar o contato de suporte, definir a moderação e ativar a política antes da abertura.</p>:status.suspended?<p>Seu acesso à participação foi suspenso. Consulte o suporte para contestar a decisão.</p>:policy.version!==COMMUNITY_POLICY_VERSION?<p>Atualize o aplicativo para ler a versão atual das regras.</p>:!accepted?<><h1>Antes de participar</h1><p>Conteúdo é revisado antes de aparecer para outras pessoas. Leia as regras para participar.</p><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Li e aceito as Regras da Comunidade</label><button disabled={!checked||busy} onClick={()=>void accept()}>Aceitar e participar</button></>:<p className="text-sm text-muted">Suas novas publicações e alterações ficam em revisão antes de aparecer para outras pessoas.</p>}</section>{allowed?<Context.Provider value={{userId,status,refresh}}>{children}</Context.Provider>:null}</>;
}
export function CommunityRules(){const [email,setEmail]=useState('');useEffect(()=>{if(!isSupabaseConfigured()) return;let active=true;void getSupabaseClient().from('community_policy').select('support_email').single().then(({data})=>{if(active)setEmail(data?.support_email??'');});return()=>{active=false;};},[]);return <main className="mx-auto max-w-3xl space-y-6 p-6"><h1>Regras da Comunidade Studify</h1>{communityRules.map(rule=><section key={rule.title}><h2>{rule.title}</h2><p>{rule.text}</p></section>)}{email?<a href={`mailto:${email}`}>{email}</a>:<p>Contato de suporte ainda em configuração.</p>}<Link href="/comunidade">Voltar à Comunidade</Link></main>;}
export function SafetyActions({kind,id,authorId}:{kind:ContentKind;id:string;authorId:string}){
 const context=useContext(Context),social=useSocial();const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[details,setDetails]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 if (!context) return null;
 const own=context?.userId===authorId,status=context?.status.reviews.find(r=>r.kind===kind&&r.id===id)?.status;
 async function report(){setBusy(true);try{const {error}=await getSupabaseClient().rpc('community_report',{p_kind:kind,p_id:id,p_reason:reason,p_details:details});if(error)throw error;setMessage('Denúncia registrada.');setOpen(false);}catch{setMessage('Não foi possível denunciar. Tente novamente ou contate o suporte.');}finally{setBusy(false);}}
 async function block(){if(!window.confirm('Bloquear esta pessoa? O conteúdo deixará de aparecer entre as duas contas.'))return;setBusy(true);try{const {error}=await getSupabaseClient().rpc('community_set_block',{p_user:authorId,p_blocked:true});if(error)throw error;await social.refresh();setMessage('Usuário bloqueado.');}catch{setMessage('Não foi possível bloquear.');}finally{setBusy(false);}}
 return <div className="mt-3 space-y-2 text-sm">{own&&status&&status!=='approved'?<p>{status==='pending'?'Em revisão · visível apenas para você':'Não aprovado · consulte as regras ou o suporte'}</p>:null}{!own?<><button className="min-h-11 px-2" disabled={busy} onClick={()=>setOpen(!open)}>Denunciar</button><button className="min-h-11 px-2" disabled={busy} onClick={()=>void block()}>Bloquear usuário</button></>:null}{open?<div className="space-y-2"><label>Motivo<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">Selecione</option>{reportReasons.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Detalhes<textarea maxLength={1000} value={details} onChange={e=>setDetails(e.target.value)}/></label><button disabled={!reason||busy} onClick={()=>void report()}>Enviar denúncia</button><button disabled={busy} onClick={()=>setOpen(false)}>Cancelar</button></div>:null}{message?<p role="status">{message}</p>:null}</div>;
}
